name: Terraform CI

on:
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "main" ] 

jobs:
  build:
    name: pr-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.7  

      - name: Terraform Run Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate
